const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('inkmap', {
  initialTheme: process.argv.includes('--inkmap-theme=dark') ? 'dark' : 'light',
  getTheme: () => ipcRenderer.invoke('appearance:get-theme'),
  setTheme: theme => ipcRenderer.invoke('appearance:set-theme', theme),
  boot: () => ipcRenderer.invoke('document:boot'),
  save: (doc, token) => ipcRenderer.invoke('document:save', doc, token),
  newDocument: folderPath => ipcRenderer.invoke('document:new', folderPath),
  library: () => ipcRenderer.invoke('library:list'),
  createFolder: (name, parentPath) => ipcRenderer.invoke('library:create-folder', name, parentPath),
  moveLibraryItem: (sourcePath, targetFolderPath) => ipcRenderer.invoke('library:move', sourcePath, targetFolderPath),
  renameLibraryItem: (sourcePath, name) => ipcRenderer.invoke('library:rename', sourcePath, name),
  deleteLibraryItem: sourcePath => ipcRenderer.invoke('library:delete', sourcePath),
  arrangeLibraryItem: (sourcePath, targetPath, position) => ipcRenderer.invoke('library:arrange', sourcePath, targetPath, position),
  onLibraryChange: callback => { const handler = () => callback(); ipcRenderer.on('library:changed', handler); return () => ipcRenderer.removeListener('library:changed', handler); },
  open: path => ipcRenderer.invoke('document:open', path),
  saveAs: (doc, token) => ipcRenderer.invoke('document:save-as', doc, token),
  exportMarkdown: (text, title) => ipcRenderer.invoke('document:export', text, title),
  exportPdf: options => ipcRenderer.invoke('document:export-pdf', options),
  copy: text => ipcRenderer.invoke('clipboard:copy', text),
  copyImage: image => ipcRenderer.invoke('clipboard:copy-image', image),
  pasteImage: availableWidth => ipcRenderer.invoke('clipboard:paste-image', availableWidth),
  copyBranch: branch => ipcRenderer.invoke('clipboard:copy-branch', branch),
  pasteBranch: () => ipcRenderer.invoke('clipboard:paste-branch'),
  pasteText: () => ipcRenderer.invoke('clipboard:paste-text'),
  reveal: () => ipcRenderer.invoke('document:reveal'),
  recent: () => ipcRenderer.invoke('document:recent'),
  onClose: callback => { const handler = () => callback(); ipcRenderer.on('window:closing', handler); return () => ipcRenderer.removeListener('window:closing', handler); },
  confirmClose: () => ipcRenderer.send('window:close-ready'),
  onOpen: callback => { const handler = (_, path) => callback(path); ipcRenderer.on('document:open-request', handler); return () => ipcRenderer.removeListener('document:open-request', handler); },
});
